portal/apps/employees/urls.py
from django.urls import path
from . import views


app_name = 'employees'
urlpatterns = [
    path('', views.employees, name='instructions'),
    path('<int:employee_id>', views.detail, name="detail")
]

portal/apps/instructions/urls.py
from django.urls import path
from . import views

app_name = 'instructions'
urlpatterns = [
    path('', views.instructions, name='instructions'),
    path('<int:instruction_id>', views.detail, name='detail')
]

portal/apps/questions/urls.py
from django.urls import path
from . import views

app_name = 'questions'
urlpatterns = [
    path('', views.questions, name='questions'),
    path('<int:question_id>', views.detail, name='detail')
]

portal/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('instruction/', include('instructions.urls')),
    path('question/', include('questions.urls')),
    path('employee/', include('employees.urls')),
    path('', index),
]

portal/apps/employees/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):
    positions = [
        ('GD', 'Генеральный директор'),
        ('GB', 'Главный бухгалтер'),
        ('ID', 'Исполнительный директор'),
    ]
    employee_fullname = models.CharField('Фамилия Имя Отчество', max_length=200)
    employee_position = models.TextField('Должность', max_length=2,
        choices=positions,
        default='GD',
    )
    employee_birthdate = models.DateField('День рождения', null=True, blank=True)

    class Meta:
        verbose_name = ("Сотрудник")
        verbose_name_plural = ("Сотрудники")

    def __str__(self):
        return self.employee_fullname


    

portal/apps/instructions/models.py
from django.db import models
# from portal.apps.employees.models import Employee

# Create your models here.

class Instruction(models.Model):
    instruction_name = models.CharField('Тема', max_length=200)
    instruction_author = models.ForeignKey('employees.Employee', on_delete=models.DO_NOTHING, null=True, verbose_name='Автор') # Автор (это поле связано с моделью Employee)
    instruction_date = models.DateTimeField('Дата создания', auto_now_add=True)
    instruction_url = models.URLField('Ссылка на инструкцию', max_length = 200)

    class Meta:
        verbose_name = ("Инструкция")
        verbose_name_plural = ("Инструкции")

    def __str__(self):
        return self.instruction_name


    

portal/apps/questions/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    themes = [
        ('FI', 'Финансы'),
        ('RT', 'Продажи'),
        ('MK', 'Маркетинг')
    ]
    question_main = models.CharField('Формулировка вопроса', max_length=200)
    question_answer = models.TextField('Ответ', max_length=1000)
    question_theme = models.TextField('Тема', max_length=2,
        choices=themes,
        default='FI',
    )

    class Meta:
        verbose_name = ("Вопрос")
        verbose_name_plural = ("Вопросы")

    def __str__(self):
        return self.question_main
    

portal/apps/employees/views.py
from django.shortcuts import render
from django.http import Http404
from .models import Employee
# Create your views here.


def employees(request):
    all_employees = Employee.objects.order_by('-employee_fullname')
    return render(request, 'employees/list.html', {'employees': all_employees})


def detail(request, employee_id):
    try:
        employee = Employee.objects.get(id=employee_id)
    except Exception:
        raise Http404(
            'Ой, кажется, такой страницы нет :(')

    return render(request, 'employees/employee.html', {'employee': employee})

portal/apps/instructions/views.py
from django.shortcuts import render
from .models import Instruction
from django.http import Http404
# Create your views here.

def instructions(request):
    all_instructions = Instruction.objects.order_by('-instruction_name')
    return render(request, 'instructions/list.html', {'instructions' : all_instructions})

def detail(request, instruction_id):
    try:
        instruction = Instruction.objects.get(id = instruction_id)
    except Exception:
        raise Http404('Ой, кажется, такой страницы нет :(')
    
    return render(request, 'instructions/instruction.html', {'instruction': instruction})

portal/apps/questions/views.py
from django.shortcuts import render
from .models import Question
from django.http import Http404
# Create your views here.


def questions(request):
    all_questions = Question.objects.order_by('-question_main')
    return render(request, 'questions/list.html', {'questions': all_questions})


def detail(request, question_id):
    try:
        question = Question.objects.get(id=question_id)
    except Exception:
        raise Http404(
            'Ой, кажется, такой страницы нет :(')

    return render(request, 'questions/question.html', {'question': question})

portal/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    return render(request, 'base.html')

portal/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %} главная страница {% endblock %}</title>
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    {% block content %}
    
<h1>Корпоративный портал</h1>
<h2>Разработчик - Кадочников А.С.</h2>
    
<a href="/employee">Сотрудники</a><br>
<a href="/instruction">Инструкции</a><br>
<a href="/question">Ответы на часто задаваемые вопросы</a>

    {% endblock %}
</html>

portal/templates/employees/employee.html
{% extends 'base.html' %}

{% block title %}{{employee.employee_fullname}} {% endblock  %}

{% block content %}

    <h1>{{ employee.employee_fullname }}</h1> 
    <p>{{ employee.get_employee_position_display }}</p>
    <p>Дата рождения: {{ employee.employee_birthdate }}</p>
        
    <h4><a href="/">Переход на главную страницу</a></h4><br>

{% endblock  %}

portal/templates/employees/list.html
{% extends 'base.html' %}

{% block title %} Список сотрудников {% endblock  %}

{% block content %}
<h1><a href="/">Главная страница</a></h1><br>

    {% if employees %}
        <ol>
        {% for employee in employees %}

            <li><a style = "font-size: 24px;" href="
                {% url 'employees:detail' employee.id %}
                ">{{employee.employee_fullname}}</a> <br></li>
            
        {% endfor %}
        </ol>
    {% endif %}

{% endblock  %}

portal/templates/instructions/instruction.html
{% extends 'base.html' %}

{% block title %}{{instruction.instruction_name}} {% endblock  %}

{% block content %}

    <h1>{{ instruction.instruction_name }}</h1> 
    <p>{{ instruction.instruction_author}}</p>
    <p><i>Опубликовано: {{ instruction.instruction_date}}</i></p>
    <p>{{ instruction.instruction_url}}</p>
        
    <h4><a href="/">Переход на главную страницу</a></h4><br>

{% endblock  %}

portal/templates/instructions/list.html
{% extends 'base.html' %}

{% block title %} Инструкции {% endblock  %}

{% block content %}
<h1><a href="/">Главная страница</a></h1><br>

    {% if instructions %}
        <ol>
        {% for instruction in instructions %}

            <li><a style = "font-size: 24px;" href="
                {% url 'instructions:detail' instruction.id %}
                ">{{instruction.instruction_name}}</a> <br></li>
            
        {% endfor %}
        </ol>
    {% endif %}

{% endblock  %}

portal/templates/questions/list.html
{% extends 'base.html' %}

{% block title %} Часто задаваемые вопросы {% endblock  %}

{% block content %}
<h1><a href="/">Главная страница</a></h1><br>

    {% if questions %}
        <ol>
        {% for question in questions %}

            <li><a style = "font-size: 24px;" href="
                {% url 'questions:detail' question.id %}
                ">{{question.question_main}}</a> <br></li>
            
        {% endfor %}
        </ol>
    {% endif %}

{% endblock  %}

portal/templates/questions/question.html
{% extends 'base.html' %}

{% block title %}{{question.question_main}} {% endblock  %}

{% block content %}

    <h1>{{ question.question_main }}</h1> 
    <p>Тема: {{ question.get_question_theme_display}}</p>
    <p>{{ question.question_answer}}</p>
    
        
    <h4><a href="/">Переход на главную страницу</a></h4><br>

{% endblock  %}